name: Automation build images
run-name: running push docker to ghcr.io

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  rules-tag:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate SemVer standard
      run: | 

          if [[ ! ${GITHUB_REF#refs/tags/} =~ ${{ vars.SEMVER_REGEX }} ]]; then 
            echo "Error: Tag $TAG_NAME tidak sesuai dengan standar SemVer!" 
            exit 1 
          else 
            echo "Tag $TAG_NAME valid menggunakan standar SemVer." 
          fi

  build-docker-image:
    needs: rules-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo -n ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build . -t ghcr.io/${{github.repository}}:latest

      - name: Push to ghcr.io
        run: docker push ghcr.io/${{github.repository}}:latest